FROM ubuntu:focal
MAINTAINER Mozul

RUN apt update  -y
RUN apt upgrade -y

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
RUN apt install -y git cmake gcc g++ gfortran liblapack-dev swig python3-dev python3-numpy python3-scipy python3-vtk7 python-is-python3
RUN apt install -y cython3
RUN apt install -y libhdf5-dev hdf5-tools python3-h5py
RUN apt install -y doxygen graphviz python3-numpydoc texlive-latex-extra dvipng imagemagick

